# class Book:
#     isbnlib = __import__('isbnlib')
#     def __init__(self, isbn13):
#         self.book = self.isbnlib(isbn13)

#         self.title = ...
#         self.genre = ...
#         self.publication_date = ...
#         self.publisher_name = ...
#         self.publisher_isbn = ...
#         self.description = ...
#         self.cover_image = ...
    
import isbnlib

isbn = '9780486602554'
book = isbnlib.meta(isbn, service='goob')
print(book)