DROP TABLE IF EXISTS USERS;

CREATE TABLE IF NOT EXISTS USERS (
    UserId INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL UNIQUE,
    Username TEXT,
    Schoolyear INTEGER,
    FirstName TEXT,
    LastName TEXT,
    Password TEXT
);
