DROP TABLE IF EXISTS BOOK_DATA;
DROP TABLE IF EXISTS GENRE;

CREATE TABLE IF NOT EXISTS GENRES (
    GenreId INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL UNIQUE,
    GenreName TEXT
);

CREATE TABLE IF NOT EXISTS BOOK_DATA (
    BookDataId INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL UNIQUE,
    ISBN TEXT,
    Title TEXT,
    AuthorId INTEGER REFERENCES AUTHORS(AuthorId),
    GenreId INTEGER REFERENCES GENRE(GenreId),
    PublicationDate TEXT,
    PublisherId INTEGER REFERENCES PUBLISHERS(PublisherId),
    Description TEXT, 
    CoverImage TEXT

);