DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS PUBLISHERS;


CREATE TABLE IF NOT EXISTS AUTHORS (
    AuthorId INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL UNIQUE,
    AuthorName TEXT
);

CREATE TABLE IF NOT EXISTS PUBLISHERS (
    PublisherId INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL UNIQUE,
    PublisherName TEXT
);
