DROP TABLE IF EXISTS BOOKS;
-- DROP TABLE IF EXISTS BORROWED_BOOKS;

-- CREATE TABLE IF NOT EXISTS BOOK_DATA (
--     Isbn TEXT PRIMARY KEY ASC NOT NULL UNIQUE,
--     Title TEXT,
--     AuthorID INTEGER REFERENCES AUTHORS(AuthorId),
--     Genre TEXT,
--     PublicationDate TEXT,
--     PublisherId INTEGER REFERENCES PUBLISHERS(PublisherId),
--     Description TEXT, 
--     CoverImage TEXT

-- );

CREATE TABLE IF NOT EXISTS BOOKS (
    BookId INTEGER PRIMARY KEY ASC AUTOINCREMENT NOT NULL UNIQUE,
    Availability INTEGER,
    BookDataIsbn INTEGER REFERENCES BOOK_DATA(Isnb)
    

    -- FOREIGN KEY (AuthorID) REFERENCES AUTHORS(AuthorId),
    -- FOREIGN KEY (PublisherId) REFERENCES PUBLISHERS(PublisherId)
);